# ~/.bashrc: executed by bash(1) for non-login shells.

# Return if not running interactively.
case $- in
    *i*) ;;
      *) return;;
esac

export DOT_FILES=DOT_FILE_LOCATION

for f in $(ls $DOT_FILES); do
	if [[ ! -d $DOT_FILES/$f && ! $DOT_FILES/$f =~ "off" ]]; then
		. $DOT_FILES/$f
	fi
done

unset f

